"""empty message

Revision ID: 0e8b0955f74d
Revises: dd9b6eeae581
Create Date: 2022-02-22 10:20:57.433970

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0e8b0955f74d'
down_revision = 'dd9b6eeae581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wx_user', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.drop_column('wx_user', 'insert_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wx_user', sa.Column('insert_time', mysql.DATETIME(), nullable=True))
    op.drop_column('wx_user', 'create_time')
    # ### end Alembic commands ###
