"""empty message

Revision ID: 518945b37e40
Revises: 0e8b0955f74d
Create Date: 2022-02-22 17:33:20.079376

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '518945b37e40'
down_revision = '0e8b0955f74d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.alter_column('wx_token', 'agent_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('wx_token', 'corp_id',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('wx_token', 'corp_secret',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('wx_token', 'access_token',
               existing_type=mysql.VARCHAR(length=512),
               nullable=True)
    op.alter_column('wx_token', 'err_msg',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('wx_token', 'insert_time',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wx_token', 'insert_time',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('wx_token', 'err_msg',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('wx_token', 'access_token',
               existing_type=mysql.VARCHAR(length=512),
               nullable=False)
    op.alter_column('wx_token', 'corp_secret',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('wx_token', 'corp_id',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('wx_token', 'agent_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.create_table('apscheduler_jobs',
    sa.Column('id', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
