"""empty message

Revision ID: 67b8d2d6a4b2
Revises: 
Create Date: 2022-02-28 14:20:00.281578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67b8d2d6a4b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wx_message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_ip', sa.String(length=40), nullable=True),
    sa.Column('from_system', sa.String(length=40), nullable=True),
    sa.Column('txn_time', sa.String(length=14), nullable=True),
    sa.Column('to_user', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('to_party', sa.Text(), nullable=True),
    sa.Column('to_tag', sa.Text(), nullable=True),
    sa.Column('msg_type', sa.String(length=50), nullable=True),
    sa.Column('agent_id', sa.String(length=10), nullable=True),
    sa.Column('msg_content', sa.Text(), nullable=True),
    sa.Column('media_id', sa.Text(), nullable=True),
    sa.Column('msg_title', sa.String(length=50), nullable=True),
    sa.Column('msg_desc', sa.String(length=100), nullable=True),
    sa.Column('msg_url', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wx_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.String(length=10), nullable=False),
    sa.Column('corp_id', sa.String(length=20), nullable=False),
    sa.Column('corp_secret', sa.String(length=50), nullable=False),
    sa.Column('access_token', sa.String(length=512), nullable=True),
    sa.Column('err_code', sa.Integer(), nullable=True),
    sa.Column('err_msg', sa.String(length=50), nullable=True),
    sa.Column('expires_in', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wx_user',
    sa.Column('emp_no', sa.String(length=10), nullable=False),
    sa.Column('wx_user_id', sa.String(length=50), nullable=True),
    sa.Column('emp_name', sa.String(length=50), nullable=True),
    sa.Column('emp_phone', sa.String(length=50), nullable=True),
    sa.Column('emp_cert_id', sa.String(length=20), nullable=True),
    sa.Column('emp_position', sa.String(length=100), nullable=True),
    sa.Column('emp_depart', sa.String(length=50), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('emp_no')
    )
    op.create_index(op.f('ix_wx_user_wx_user_id'), 'wx_user', ['wx_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wx_user_wx_user_id'), table_name='wx_user')
    op.drop_table('wx_user')
    op.drop_table('wx_token')
    op.drop_table('wx_message')
    # ### end Alembic commands ###
