"""empty message

Revision ID: dd9b6eeae581
Revises: 2e8be84a9249
Create Date: 2022-02-22 10:20:18.362474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd9b6eeae581'
down_revision = '2e8be84a9249'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wx_user',
    sa.Column('emp_no', sa.String(length=10), nullable=False),
    sa.Column('wx_user_id', sa.String(length=50), nullable=True),
    sa.Column('emp_name', sa.String(length=50), nullable=True),
    sa.Column('emp_phone', sa.String(length=50), nullable=True),
    sa.Column('emp_cert_id', sa.String(length=20), nullable=True),
    sa.Column('emp_position', sa.String(length=100), nullable=True),
    sa.Column('emp_depart', sa.String(length=50), nullable=True),
    sa.Column('insert_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('emp_no')
    )
    op.create_index(op.f('ix_wx_user_wx_user_id'), 'wx_user', ['wx_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wx_user_wx_user_id'), table_name='wx_user')
    op.drop_table('wx_user')
    # ### end Alembic commands ###
