"""empty message

Revision ID: f981094a4424
Revises: 518945b37e40
Create Date: 2022-02-22 17:34:43.301824

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f981094a4424'
down_revision = '518945b37e40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wx_token', 'agent_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('wx_token', 'corp_id',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('wx_token', 'corp_secret',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wx_token', 'corp_secret',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('wx_token', 'corp_id',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('wx_token', 'agent_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###
